### ISSUE TITLE
New Advertiser (LS) not showing up, but new links for that advertiser are. 

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#68]
@cgladue Thought this was kind of strange, but maybe you know why. https://screencast.com/t/NtQ62WI0VcqI

**Comment by cgladue** [comment]
Yea it wasnt changed to Joined till the engine ran again little after you posted this, the advertisers and links only update every 24 hours ... and there was a bug for LS advertisers changing from notjoined to joined writing to the activity stream i fixed, so should be all set.

**Comment by robgpeak** [comment]
OK, so now I see Skarlett Bule in the http://shop.complinks.co/admindashboard/advertisers as joined, but I still don't see it in the activity stream when I search "new advertiser" (which is how LS shows up in the stream, while cj advertisers show up when you search "joined"

**Comment by cgladue** [comment]
correct because when it went from notjoined to joined there was a bug that never wrote to the activity stream, so thats why its not there, but as stated above that should be corrected now.

**Comment by robgpeak** [comment]
OK, I will test again today/tomorrow to see if is it working as planned before marking this as closed.
