### ISSUE TITLE
Pull Featured Deals

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#84]
We have two requirements defined for pulling "Featured Deals," one on the homepage, the other in the primary navigation. The initial implementation will be to pull the first active deal from a Featured Advertiser, but the next step would be to allow admins to feature a deal (link) on the admin side.

**Comment by ChrisASearles** [comment]
Hey @cgladue I just checked in a bunch of updates. I pulled all the layout stuff into partials, built a new controller to host all the child actions for the layout and added/updated some view models for all that data. I was going to pull the featured links as described above but there aren't any nav properties on the Advertiser object for links so I wasn't sure if you wanted to build this as a stored proc, as a separate method in one of your DAL's, or how else you might want to handle it so I figured I'd leave it for you.

**Comment by cgladue** [comment]
i was just finishing up adding that when i saw this, its ok i deleted my code and kept yours during the conflict... also i went in and added the featuredDeal call to the DAL and your VM its committed to SVN now if you do an update

**Comment by cgladue** [comment]
i have implemented what you wanted with advertiser links being able to be featured... the LinkDAL.getFeaturedDeals(string username) call is where you get it from.

**Comment by ChrisASearles** [comment]
Hey @cgladue I see the method and that you added it to the controller action but I'm not getting any data back. Am I missing something on the admin side I need to do?

**Comment by cgladue** [comment]
there are probbally no "Deals" (Links) assigned as Featured

https://shop.complinks.co/admindashboard/advertisers/links/11  you can set
as featured from there.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by ChrisASearles** [comment]
Great, thanks.

**Comment by ChrisASearles** [comment]
@cgladue I marked a few links as featured, ensured the advertiser was joined and active and the links were active and not expired and I'm still not seeing them. Committed my current version to the repo, can you take a look and see if I'm missing something?

**Comment by cgladue** [comment]
can you update your repo and try it now, i was returning an empty list.  should of returned a different object.

**Comment by ChrisASearles** [comment]
This is working. @robgpeak I think we need to discuss the featured deals in the nav's, I don't think it works as is and we should probably just link to a new page that displays featured deals. I'm going to create that as a new issue since it's only related to the menus and submit this one for review with that understanding.

**Comment by robgpeak** [comment]
agreed, the link in the nav should go to a page.

**Comment by robgpeak** [comment]
It is pulling the featured deals, so I will close this particular issue, but the functionality of it will brought up in another issue.

**Comment by robgpeak** [comment]
@ChrisASearles You mentioned a few days ago that you didn't think the featured deals in the nav menu worked well, and I agreed.  You mentioned you were going to create a new issue, but I did a search for one and did not see anything.  I did not want to step on your toes here and duplicate something you may have already created and I just can't find...

**Comment by robgpeak** [comment]
@ChrisASearles perhaps in the effort of working on more pressing issues, we can remove the link from the nav menu and table it for a future release.
